spring:
    profiles:
        active: local
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
        static-path-pattern: /**
    web:
        resources:
            static-locations: classpath:/static/
    datasource:
        #url: jdbc:mariadb://localhost:3306/ias
        #driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:log4jdbc:mariadb://localhost:3306/ias?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul 
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: iasuser
        password: ias1234!@        
    servlet:
        multipart:
            location: /tobe/storage/ias/tmp

mybatis:
    mapper-locations: classpath:mappers/**/**.xml
    type-aliases-package: com.korigin.tobe.ias.model
    configuration:
        map-underscore-to-camel-case: true

app:
    upload:
        root-path: /tobe/storage/ias
        resource-handler: /upload/**